# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/桌面/CPU_test4fromcsdn/.Xil/Vivado-6268-DESKTOP-FBGS9FI/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/bd/design_1/synth/design_1.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ADR.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ALU.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ALUoutDR.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/BDR.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ControlUnit.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DBDR.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DFileFlop.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataMEM.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_2to1.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_2to1_sa.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_3to1.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_4to1.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/IR.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/InstructionMEM.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/NextState.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/OutputFunc.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PC.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PCAddFour.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PCAddImm.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PCJump.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/RegFile.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/SignExtend.v
      D:/桌面/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/Main.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Main
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/桌面/CPU_test4fromcsdn/.Xil/Vivado-6268-DESKTOP-FBGS9FI/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
