"""empty message

Revision ID: 042b9df60055
Revises: 
Create Date: 2022-06-15 16:03:59.786102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042b9df60055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_na', sa.String(length=20), nullable=False),
    sa.Column('c_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('c_na')
    )
    op.create_table('computerroom',
    sa.Column('cr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cr_adr', sa.String(length=20), nullable=False),
    sa.Column('cr_na', sa.String(length=20), nullable=False),
    sa.Column('cr_num', sa.Integer(), nullable=False),
    sa.Column('use_num', sa.Integer(), nullable=False),
    sa.Column('use', sa.String(length=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('cr_id'),
    sa.UniqueConstraint('cr_adr'),
    sa.UniqueConstraint('cr_na')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_na', sa.String(length=10), nullable=False),
    sa.Column('user_pw', sa.String(length=30), nullable=False),
    sa.Column('power', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_na')
    )
    op.create_table('creservation',
    sa.Column('crs_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('crs_time', sa.DateTime(), nullable=True),
    sa.Column('crs_long', sa.SmallInteger(), nullable=True),
    sa.Column('coment', sa.String(length=20), nullable=True),
    sa.Column('finish', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['class.c_id'], ),
    sa.ForeignKeyConstraint(['cr_id'], ['computerroom.cr_id'], ),
    sa.PrimaryKeyConstraint('crs_id', 'c_id')
    )
    op.create_table('student',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_na', sa.String(length=10), nullable=True),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('s_money', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['class.c_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('one',
    sa.Column('o_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('cr_id', sa.Integer(), nullable=True),
    sa.Column('s_start', sa.DateTime(), nullable=True),
    sa.Column('s_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cr_id'], ['computerroom.cr_id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['student.s_id'], ),
    sa.PrimaryKeyConstraint('o_id'),
    sa.UniqueConstraint('s_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one')
    op.drop_table('student')
    op.drop_table('creservation')
    op.drop_table('user')
    op.drop_table('computerroom')
    op.drop_table('class')
    # ### end Alembic commands ###
