# Project: 二叉树（实验六）
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main3.o BinaryTree.o OrderBinaryTree.o
LINKOBJ  = main3.o BinaryTree.o OrderBinaryTree.o
LIBS     = -L"D:/Dev C++/Dev-Cpp/MinGW32/lib" -L"D:/Dev C++/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -g3
INCS     = -I"D:/Dev C++/Dev-Cpp/MinGW32/include" -I"D:/Dev C++/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Dev C++/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"D:/Dev C++/Dev-Cpp/MinGW32/include" -I"D:/Dev C++/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Dev C++/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"D:/Dev C++/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = 二叉树（实验六）.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main3.o: main3.cpp
	$(CPP) -c main3.cpp -o main3.o $(CXXFLAGS)

BinaryTree.o: BinaryTree.cpp
	$(CPP) -c BinaryTree.cpp -o BinaryTree.o $(CXXFLAGS)

OrderBinaryTree.o: OrderBinaryTree.cpp
	$(CPP) -c OrderBinaryTree.cpp -o OrderBinaryTree.o $(CXXFLAGS)
