HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'computer'
USERNAME = 'root'
PASSWORD = 'yanping2001'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False