# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param synth.elaboration.rodinMoreOptions {rt::set_parameter enableTristateBubbleUp 1}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.cache/wt [current_project]
set_property parent.project_path D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ADR.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ALU.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ALUoutDR.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/BDR.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/ControlUnit.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DBDR.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DFileFlop.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataMEM.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_2to1.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_2to1_sa.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_3to1.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/DataSelector_4to1.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/IR.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/InstructionMEM.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/NextState.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/OutputFunc.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PC.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PCAddFour.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PCAddImm.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/PCJump.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/RegFile.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/SignExtend.v
  D:/Vivado/WorkSpace/CPU_test4fromcsdn/CPU_test4fromcsdn.srcs/sources_1/new/Main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
